### ISSUE TITLE
Program to compute the callgraph

### ISSUE THREAD

**Issue by brucou** [asgerf/callgraphjs#1]
I have a question which might sound stupid but I could not find the program that would generate the call graph. Could you indicate me the path to it?

**Comment by asgerf** [comment]
Not a stupid question at all, but the original implementation is inaccessible, even to me.

I made a [basic reimplementation](https://github.com/asgerf/callgraphjs.dart) that you can use see how the algorithm works.

**Comment by brucou** [comment]
wow. That sounds like an intellectual property issue. Alright and thanks, will have a look. Good opportunity to see some actual Dart code.
